[package]
name = "luciuz-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
luciuz-config = { path = "../luciuz-config" }
